import type { Metadata } from "next";
import "./globals.css";
import TopHeader from "@/components/TopHeader";
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Exclusive | The Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <TopHeader/>
        <Header/>
        <main className=" mx-auto max-w-[1440px] container">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
